<a href="https://colab.research.google.com/github/loicdaloz/etfdata/blob/main/000_Extraction_yfinance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# install a library
!pip install yfinance

In [5]:
# import libraries
import yfinance as yf
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [14]:
from google.colab import files
files.upload()

Saving etf.csv to etf (3).csv

{'etf.csv': b'TICKER\r\nSPY\r\nGLD\r\nVWO\r\nEEM\r\nEFA\r\nQQQ\r\nIVV\r\nTIP\r\nVTI\r\nLQD\r\nIWF\r\nIWM\r\nBND\r\nAGG\r\nHYG\r\nIWD\r\nDIA\r\nJNK\r\nVNQ\r\nIJH\r\nVIG\r\nEWZ\r\nDVY\r\nMDY\r\nSHY\r\nSLV\r\nIAU\r\nXLK\r\nSDY\r\nCSJ\r\nPFF\r\nXLE\r\nVEA\r\nIJR\r\nBSV\r\nXLF\r\nVUG\r\nIVW\r\nIWB\r\nVEU\r\nIWR\r\nGDX\r\nFXI\r\nXLU\r\nMOO\r\nDBC\r\nVTV\r\nEWJ\r\nXLP\r\nMBB\r\nEWC\r\nIVE\r\nCIU\r\nIEF\r\nVB\r\nEMB\r\nAMJ\r\nIWO\r\nXLV\r\nIWN\r\nIYR\r\nVO\r\nTBT\r\nIWP\r\nOEF\r\nDEM\r\nXLI\r\nEWY\r\nEPP\r\nIWV\r\nVV\r\nEWG\r\nXLY\r\nIWS\r\nVYM\r\nRSP\r\nIJK\r\nBIV\r\nTLT\r\nVOO\r\nMUB\r\nAMLP\r\nVCSH\r\nEWA\r\nVGK\r\nICF\r\nRWX\r\nACWI\r\nEWT\r\nDJP\r\nAAXJ\r\nSHV\r\nVGT\r\nIJS\r\nIJJ\r\nIEI\r\nRSX\r\nVBK\r\nILF\r\n'}

In [16]:
# read the CSV file containing the ETF ticker list
ticker_list = pd.read_csv('etf (3).csv', usecols=[0])
print(ticker_list)

   TICKER
0     SPY
1     GLD
2     VWO
3     EEM
4     EFA
..    ...
94    IJJ
95    IEI
96    RSX
97    VBK
98    ILF

[99 rows x 1 columns]

In [18]:
import yfinance as yf
import pandas as pd

# Load the ticker symbols from the CSV file
df = pd.read_csv('etf (3).csv')

# Create an empty DataFrame to store the historical prices
prices = pd.DataFrame()

# Loop over each ticker symbol in the CSV file
for ticker in df['TICKER']:
    # Use yfinance to retrieve the historical prices for the ticker
    ticker_prices = yf.download(ticker, start='2010-01-01', end='2023-03-23')
    
    # Add a column to the DataFrame with the ticker symbol
    ticker_prices['TICKER'] = ticker
    
    # Append the ticker's historical prices to the overall DataFrame
    prices = pd.concat([prices, ticker_prices])

# Save the historical prices to a new CSV file
prices.to_csv('historical_prices.csv')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [19]:
etfprices = pd.read_csv('historical_prices.csv')

In [20]:
etfprices.head()

,Date,Open,High,Low,Close,Adj Close,Volume,TICKER
0,2010-01-04,112.370003,113.389999,111.510002,113.330002,88.117889,118944600,SPY
1,2010-01-05,113.260002,113.680000,112.849998,113.629997,88.351143,111579900,SPY
2,2010-01-06,113.519997,113.989998,113.430000,113.709999,88.413353,116074400,SPY
3,2010-01-07,113.500000,114.330002,113.180000,114.190002,88.786606,131091100,SPY
4,2010-01-08,113.889999,114.620003,113.660004,114.570000,89.082024,126402800,SPY

In [22]:
etfprices = etfprices.pivot_table(values='Adj Close', index='Date', columns='TICKER')

In [ ]:
etfprices.head()

Ticker,AAXJ,ACWI,AGG,AMJ,AMLP,BIV,BND,BSV,CIU,CSJ,...,VWO,VYM,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,44.931618,32.882568,73.482346,12.362126,NaN,50.767067,54.585270,63.214291,103.230003,104.019997,...,29.967363,25.556835,38.080154,9.385942,21.880177,19.150223,18.718462,19.481916,25.213636,25.227163
2010-01-05,45.434616,33.156841,73.816620,12.531465,NaN,51.035652,54.744854,63.373051,103.349998,104.250000,...,30.066313,25.556835,38.390972,9.558458,21.957445,19.125532,18.725481,19.249989,24.966366,25.319675
2010-01-06,45.395325,33.149223,73.773979,12.539938,NaN,50.901356,54.724049,63.325432,103.330002,104.250000,...,30.250072,25.609940,38.850708,9.577624,22.003799,18.911564,18.711441,19.362823,25.221605,25.353306
2010-01-07,45.175255,32.989235,73.688629,12.383295,NaN,50.837391,54.682407,63.341290,103.379997,104.269997,...,29.988564,25.656401,38.792423,9.782084,22.243319,18.837502,18.711441,19.275063,25.309351,25.563532
2010-01-08,45.356018,33.194939,73.731293,12.578036,NaN,50.952503,54.737949,63.325432,103.529999,104.400002,...,30.172329,25.702875,39.044960,9.724579,22.598713,18.960943,18.648275,19.256256,25.349237,25.555124

In [23]:
returns = etfprices.pct_change()

In [24]:
returns.head()

TICKER,AAXJ,ACWI,AGG,AMJ,AMLP,BIV,BND,BSV,CIU,CSJ,...,VWO,VYM,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05,0.011194,0.008341,0.004550,0.013699,NaN,0.005291,0.002924,0.002512,0.001162,0.002211,...,0.003302,0.000000,0.008162,0.018380,0.003531,-0.001289,0.000375,-0.011905,-0.009807,0.003667
2010-01-06,-0.000865,-0.000230,-0.000578,0.000676,NaN,-0.002632,-0.000381,-0.000752,-0.000193,0.000000,...,0.006112,0.002078,0.011975,0.002006,0.002111,-0.011187,-0.000749,0.005861,0.010223,0.001328
2010-01-07,-0.004848,-0.004827,-0.001156,-0.012492,NaN,-0.001257,-0.000761,0.000251,0.000484,0.000192,...,-0.008645,0.001814,-0.001500,0.021347,0.010885,-0.003916,0.000000,-0.004532,0.003479,0.008292
2010-01-08,0.004002,0.006236,0.000578,0.015726,NaN,0.002264,0.001015,-0.000251,0.001451,0.001247,...,0.006128,0.001811,0.006510,-0.005878,0.015978,0.006553,-0.003376,-0.000976,0.001576,-0.000329